import{a as k,s as T,h as E,b as q,c as _,d as D,o as w,e as x}from"./assets/main-BWRRlNVk.js";import"./assets/vendor-D5rSzIS2.js";const B="https://image.tmdb.org/t/p/original",I=1900,P=document.querySelector("#catalogSearchForm"),l=document.querySelector("#catalogSearchInput"),p=document.querySelector("#catalogClearBtn"),S=document.querySelector("#catalogYearSelect"),u=document.querySelector("#catalogList"),r=document.querySelector("#catalogMessage"),d=document.querySelector("#catalogPagination"),h=document.querySelector("#catalogHero"),M=document.querySelector("#catalogHeroContent"),R=document.querySelector("#catalogHeroTitle"),Y=document.querySelector("#catalogHeroRating"),A=document.querySelector("#catalogHeroDescription"),f=document.querySelector("#catalogHeroMessage"),F=document.querySelector("#catalogHeroTrailerBtn"),N=document.querySelector("#catalogHeroDetailsBtn");let y=[],o=1,c="",g="",i=null;function O(){const e=new Date().getFullYear();for(let t=e;t>=I;t-=1){const n=document.createElement("option");n.value=t,n.textContent=t,S.append(n)}}function H(){const e=l.value.trim()==="";p.classList.toggle("is-hidden",e)}function K(){l.value="",p.classList.add("is-hidden"),l.focus()}function G(e){return typeof e=="number"?e.toFixed(1):"0.0"}function W(e){if(Array.isArray(e.genres))return e;const t=(e.genre_ids||[]).map(n=>y.find(a=>a.id===n)).filter(Boolean);return{...e,genres:t}}function $(e){if(!e){i=null,M.hidden=!0,f.hidden=!1,f.textContent="We are sorry, but we could not find a movie for today.",h.style.backgroundImage="none";return}i=e.id,f.hidden=!0,M.hidden=!1,R.textContent=e.title||"Unknown movie",A.textContent=e.overview||"No description available.",Y.textContent=`★ ${G(e.vote_average)} / 10`,h.style.backgroundImage=e.backdrop_path?`url("${B}${e.backdrop_path}")`:"none"}function U(e){if(!(e!=null&&e.length))return null;const t=new Date,n=new Date(t.getFullYear(),0,0),s=Math.floor((t-n)/864e5)%e.length;return e[s]}function L(e){u.innerHTML="",d.innerHTML="",r.classList.remove("catalog-message--empty"),r.textContent=e,r.hidden=!1}function V(){u.innerHTML="",d.innerHTML="",r.innerHTML=`
    <span class="catalog-message__title">
      OOPS
    </span>

    <span class="catalog-message__subtitle">
      We are very sorry!
    </span>

    <span class="catalog-message__text">
      We don’t have any results matching your search.
    </span>
  `,r.classList.add("catalog-message--empty"),r.hidden=!1}function j(e){if(!(e!=null&&e.length)){V();return}r.hidden=!0,u.innerHTML=e.map(t=>{const n=W(t);return _(n)}).join("")}function Q(e){const t=document.createElement("button");return t.type="button",t.textContent=e,t.dataset.page=e,e===o&&t.classList.add("is-active"),t}function z(e,t){if(o=e,d.innerHTML="",t<=1)return;const n=Math.max(1,o-2),a=Math.min(t,o+2);for(let s=n;s<=a;s+=1)d.append(Q(s))}async function v(e,t,n={}){T();try{const a=await e();j(a.results),z(a.page,a.total_pages),n.updateHero&&$(U(a.results))}catch{L(t)}finally{E()}}function m(e=1){return v(()=>q(e),"Something went wrong while loading movies.",{updateHero:e===1})}function b(e,t,n=1){return v(()=>D(e,t,n),"Something went wrong while searching movies.")}function C(e){if(!e)return;const t=Number(e.dataset.id);w(t)}function J(e){const t=e.target.closest(".movie-card");C(t)}function X(e){const t=e.target.closest(".movie-card");!t||!(e.key==="Enter"||e.key===" ")||(e.preventDefault(),C(t))}async function Z(e){if(e.preventDefault(),c=l.value.trim(),g=S.value,o=1,!c&&g){L("Please enter a movie name to search by year.");return}if(!c){await m(1);return}await b(c,g,o)}async function ee(){i&&await x(i)}function te(){i&&w(i)}async function ne(e){const t=e.target.closest("button");t&&(o=Number(t.dataset.page),c?await b(c,g,o):await m(o),window.scrollTo({top:h.offsetHeight,behavior:"smooth"}))}function ae(){l.addEventListener("input",H),p.addEventListener("click",K),P.addEventListener("submit",Z),u.addEventListener("click",J),u.addEventListener("keydown",X),F.addEventListener("click",ee),N.addEventListener("click",te),d.addEventListener("click",ne)}async function oe(){try{y=await k()}catch{y=[]}}async function re(){O(),H(),ae(),await oe(),await m()}re();
//# sourceMappingURL=catalog.js.map
