import{a as S,s as b,h as C,b as E,c as k,d as T,o as _}from"./assets/main-QZfbdKYR.js";import"./assets/vendor-D5rSzIS2.js";const P=1900,q=document.querySelector("#catalogSearchForm"),s=document.querySelector("#catalogSearchInput"),m=document.querySelector("#catalogClearBtn"),p=document.querySelector("#catalogYearSelect"),c=document.querySelector("#catalogList"),r=document.querySelector("#catalogMessage"),i=document.querySelector("#catalogPagination"),g=document.querySelector(".catalog-section");let f=[],a=1,o="",l="";function H(){const e=new Date().getFullYear();for(let t=e;t>=P;t-=1){const n=document.createElement("option");n.value=t,n.textContent=t,p.append(n)}}function y(){const e=s.value.trim()==="";m.classList.toggle("is-hidden",e)}function I(){s.value="",m.classList.add("is-hidden"),s.focus()}function A(e){if(Array.isArray(e.genres))return e;const t=(e.genre_ids||[]).map(n=>f.find(u=>u.id===n)).filter(Boolean);return{...e,genres:t}}function v(e){c.innerHTML="",i.innerHTML="",r.classList.remove("catalog-message--empty"),r.textContent=e,r.hidden=!1}function Y(){c.innerHTML="",i.innerHTML="",r.innerHTML=`
    <span class="catalog-message__title">
      OOPS
    </span>

    <span class="catalog-message__subtitle">
      We are very sorry!
    </span>

    <span class="catalog-message__text">
      We don’t have any results matching your search.
    </span>
  `,r.classList.add("catalog-message--empty"),r.hidden=!1}function x(e){if(!(e!=null&&e.length)){Y();return}r.hidden=!0,c.innerHTML=e.map(t=>{const n=A(t);return k(n)}).join("")}function B(e){const t=document.createElement("button");return t.type="button",t.textContent=e,t.dataset.page=e,e===a&&t.classList.add("is-active"),t}function F(e,t){if(a=e,i.innerHTML="",t<=1)return;const n=Math.max(1,a-2),u=Math.min(t,a+2);for(let d=n;d<=u;d+=1)i.append(B(d))}async function M(e,t){b();try{const n=await e();x(n.results),F(n.page,n.total_pages)}catch{v(t)}finally{C()}}function h(e=1){return M(()=>E(e),"Something went wrong while loading movies.")}function L(e,t,n=1){return M(()=>T(e,t,n),"Something went wrong while searching movies.")}function w(e){if(!e)return;const t=Number(e.dataset.id);_(t)}function R(e){const t=e.target.closest(".movie-card");w(t)}function N(e){const t=e.target.closest(".movie-card");!t||!(e.key==="Enter"||e.key===" ")||(e.preventDefault(),w(t))}async function O(e){if(e.preventDefault(),o=s.value.trim(),l=p.value,a=1,!o&&l){v("Please enter a movie name to search by year.");return}if(!o){await h(1);return}await L(o,l,a)}async function D(e){const t=e.target.closest("button");t&&(a=Number(t.dataset.page),o?await L(o,l,a):await h(a),g==null||g.scrollIntoView({behavior:"smooth",block:"start"}))}function G(){s.addEventListener("input",y),m.addEventListener("click",I),q.addEventListener("submit",O),c.addEventListener("click",R),c.addEventListener("keydown",N),i.addEventListener("click",D)}async function K(){try{f=await S()}catch{f=[]}}async function V(){H(),y(),G(),await K(),await h()}V();
//# sourceMappingURL=catalog.js.map
